module GHC.Stack.Profiler.Core.Internal (
  CallStackFrameTag (..),
  MessageTag (..),
  ShortText (..),
  callStackFrameMaxSize,
  callStackFrameSize,
  callStackFrameTagSize,
  callStackMaxLen,
  callStackMaxLen',
  capabilityIdSize,
  ipeIdSize,
  messageMaxSize,
  messageMinSize,
  messageTagSize,
  sourceLocationDefSize,
  sourceLocationIdSize,
  stringDefBodyMaxSize,
  stringIdSize,
  threadIdSize,
  toShortText,
  truncateTextToByteLimit,
  chunkCallStack,
  chunkCallStack_,
) where

import GHC.Stack.Profiler.Core.Dehydrate (
  chunkCallStack,
  chunkCallStack_,
 )
import GHC.Stack.Profiler.Core.Eventlog (
  CallStackFrameTag (..),
  MessageTag (..),
  ShortText (..),
  callStackFrameMaxSize,
  callStackFrameSize,
  callStackFrameTagSize,
  callStackMaxLen,
  callStackMaxLen',
  capabilityIdSize,
  ipeIdSize,
  messageMaxSize,
  messageMinSize,
  messageTagSize,
  sourceLocationDefSize,
  sourceLocationIdSize,
  stringDefBodyMaxSize,
  stringIdSize,
  threadIdSize,
  toShortText,
  truncateTextToByteLimit,
 )
